# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactDemo

  target 'ReactDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

